version: "3.8"
services:
  django:
    build: 
      context: .
    networks:
      - subnet-web-ngd
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "8000:8000"
    networks:
      - subnet-web-ngd
networks:
  subnet-web-ngd:
    ipam:
      config:
        - subnet: 172.18.0.0/16
